# Generated by Django 4.0.3 on 2022-03-04 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_breed_exerciseneeds_alter_breed_friendliness_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='dog',
            name='favorittoy',
        ),
        migrations.AddField(
            model_name='dog',
            name='favoritetoy',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dog',
            name='favoritefood',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
